# Generated by Django 5.2.5 on 2025-08-29 06:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="계좌번호"
                    ),
                ),
                ("bank_code", models.CharField(max_length=10, verbose_name="은행코드")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "일반예금"),
                            ("savings", "적금"),
                            ("loan", "마이너스통장"),
                            ("deposit", "정기예금"),
                        ],
                        max_length=20,
                        verbose_name="계좌유형",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="잔액",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌들",
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="거래금액"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="거래후잔액"
                    ),
                ),
                (
                    "transaction_detail",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="거래내역상세",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "입금"), ("withdrawal", "출금")],
                        max_length=20,
                        verbose_name="거래유형",
                    ),
                ),
                (
                    "detail_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deposit", "입금"),
                            ("transfer", "계좌이체"),
                            ("auto_transfer", "자동이체"),
                            ("card_payment", "카드결제"),
                            ("atm_withdrawal", "ATM출금"),
                            ("interest", "이자입금"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="상세유형",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(db_index=True, verbose_name="거래일시"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                        verbose_name="계좌",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래내역",
                "verbose_name_plural": "거래내역들",
                "db_table": "transaction_history",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "account_number"], name="accounts_user_id_616643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_number"], name="accounts_account_2815ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["balance"], name="accounts_balance_acc40f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user", "account_number")},
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["account", "transaction_date"],
                name="transaction_account_e885df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["transaction_date"], name="transaction_transac_f34dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["transaction_type"], name="transaction_transac_5837b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["created_at"], name="transaction_created_5a5299_idx"
            ),
        ),
    ]
