# Generated by Django 5.2.5 on 2025-09-02 11:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="계좌번호"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="사용자가 지정한 계좌 별칭",
                        max_length=100,
                        verbose_name="계좌명",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("001", "KB국민은행"),
                            ("002", "신한은행"),
                            ("003", "우리은행"),
                            ("004", "NH농협은행"),
                            ("005", "IBK기업은행"),
                            ("006", "하나은행"),
                            ("007", "SC제일은행"),
                            ("008", "카카오뱅크"),
                            ("009", "토스뱅크"),
                            ("010", "케이뱅크"),
                        ],
                        max_length=10,
                        verbose_name="은행코드",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "일반예금"),
                            ("savings", "적금"),
                            ("loan", "마이너스통장"),
                            ("deposit", "정기예금"),
                            ("investment", "투자계좌"),
                        ],
                        default="checking",
                        max_length=20,
                        verbose_name="계좌유형",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="잔액",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주계좌 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌들",
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="거래금액",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="거래후잔액"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "입금"),
                            ("withdrawal", "출금"),
                            ("transfer_in", "이체입금"),
                            ("transfer_out", "이체출금"),
                        ],
                        max_length=20,
                        verbose_name="거래유형",
                    ),
                ),
                (
                    "detail_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash_deposit", "현금입금"),
                            ("transfer", "계좌이체"),
                            ("auto_transfer", "자동이체"),
                            ("card_payment", "카드결제"),
                            ("atm_withdrawal", "ATM출금"),
                            ("online_transfer", "온라인이체"),
                            ("mobile_transfer", "모바일이체"),
                            ("interest", "이자입금"),
                            ("fee", "수수료"),
                            ("salary", "급여"),
                            ("refund", "환불"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="상세유형",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="거래 설명", max_length=200, verbose_name="거래내역"
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="사용자 메모",
                        max_length=500,
                        verbose_name="메모",
                    ),
                ),
                (
                    "counterpart_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="상대방계좌"
                    ),
                ),
                (
                    "counterpart_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="상대방명"
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(db_index=True, verbose_name="거래일시"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                        verbose_name="계좌",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래내역",
                "verbose_name_plural": "거래내역들",
                "db_table": "transaction_history",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "account_number"], name="accounts_user_id_616643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_number"], name="accounts_account_2815ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["balance"], name="accounts_balance_acc40f_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["is_active"], name="accounts_is_acti_5b02bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["created_at"], name="accounts_created_1b6d37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user", "account_number")},
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["account", "transaction_date"],
                name="transaction_account_e885df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["transaction_date"], name="transaction_transac_f34dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["transaction_type"], name="transaction_transac_5837b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["detail_type"], name="transaction_detail__420438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["created_at"], name="transaction_created_5a5299_idx"
            ),
        ),
    ]
