# Generated by Django 5.2.5 on 2025-08-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=1000, verbose_name="메시지")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("transaction", "거래알림"),
                            ("analysis", "분석알림"),
                            ("system", "시스템알림"),
                            ("budget", "예산알림"),
                        ],
                        default="system",
                        max_length=50,
                        verbose_name="알림유형",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="읽음여부"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림들",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
