# Generated by Django 5.2.5 on 2025-08-29 06:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="총수입",
                    ),
                ),
                (
                    "total_expense",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="총지출",
                    ),
                ),
                (
                    "savings_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="저축금액",
                    ),
                ),
                (
                    "analysis_period",
                    models.CharField(
                        choices=[
                            ("daily", "일"),
                            ("weekly", "주"),
                            ("monthly", "월"),
                            ("yearly", "년"),
                            ("custom", "사용자정의"),
                        ],
                        max_length=20,
                        verbose_name="분석기간",
                    ),
                ),
                (
                    "ai_analysis",
                    models.TextField(blank=True, null=True, verbose_name="AI분석결과"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="설명"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(db_index=True, verbose_name="분석시작일"),
                ),
                (
                    "period_end",
                    models.DateField(db_index=True, verbose_name="분석종료일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "분석",
                "verbose_name_plural": "분석들",
                "db_table": "analysis",
                "ordering": ["-created_at"],
            },
        ),
    ]
