# Generated by Django 5.2.5 on 2025-08-30 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.CharField(max_length=100, verbose_name="분석 주제")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="주기",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(db_index=True, verbose_name="분석 시작일"),
                ),
                (
                    "period_end",
                    models.DateField(db_index=True, verbose_name="분석 종료일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="analysis_results/",
                        verbose_name="결과 이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석",
                "verbose_name_plural": "분석들",
                "db_table": "analysis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="analysis_user_id_a30a3f_idx",
                    ),
                    models.Index(
                        fields=["user", "period_start", "period_end"],
                        name="analysis_user_id_ba9109_idx",
                    ),
                    models.Index(fields=["type"], name="analysis_type_d46e40_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_start__lte", models.F("period_end"))
                        ),
                        name="analysis_period_order_ok",
                    )
                ],
            },
        ),
    ]
