# Generated by Django 5.2.5 on 2025-08-29 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["user", "period_start", "period_end"],
                name="analysis_user_id_ba9109_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["period_start"], name="analysis_period__ac248a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["period_end"], name="analysis_period__9eefe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["created_at"], name="analysis_created_43d70b_idx"
            ),
        ),
    ]
